
development:
  adapter: postgresql
  database: synthfinder_development
  host: localhost
  port: 5432

production:
  adapter: postgresql
  database: synthfinder_production
  host: localhost
  port: 5432
